# Generated by Django 4.1.1 on 2023-04-09 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("iq_test", "IQ Test"),
                            ("soft_skill", "Soft Skill"),
                            ("professional_test", "Professional Test"),
                        ],
                        max_length=32,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "user_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_action_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "tg_user",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("famale", "Famale"), ("male", "Male")], max_length=8
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("cv", models.FileField(upload_to="cv/%Y/%m/%d/")),
                ("specialization", models.ManyToManyField(to="gpt_bot.specialization")),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gpt_bot.telegramuser",
                    ),
                ),
            ],
        ),
    ]
