# Generated by Django 3.2.13 on 2023-04-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_bot', '0002_question_index_alter_flowprocess_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpt_bot.flowprocess'),
        ),
    ]
