# Generated by Django 3.2.13 on 2023-04-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_bot', '0003_question_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowprocess',
            name='iq_test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowprocess',
            name='professional_test_main_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowprocess',
            name='professional_test_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowprocess',
            name='soft_skill_main_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowprocess',
            name='soft_skill_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
