# Generated by Django 4.1.1 on 2023-04-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt_bot", "0004_auto_20230409_1940"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="flowprocess",
            name="region",
        ),
    ]
