# Generated by Django 4.1.1 on 2023-04-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gpt_bot", "0005_region_remove_flowprocess_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowprocess",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gpt_bot.region",
            ),
        ),
    ]
