# Generated by Django 4.1.1 on 2023-04-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt_bot", "0006_flowprocess_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("phone_number", models.CharField(max_length=255)),
                ("limit", models.IntegerField(default=0)),
                ("used", models.IntegerField(default=0)),
            ],
        ),
    ]
