# Generated by Django 4.1.1 on 2023-06-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt_bot", "0007_userlimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowprocess",
            name="generated_resume",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
